image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      yarn install --force
      gp sync-done install
    command: yarn dev
  - init: gp sync-await install
    command: yarn cy:open
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
  - port: 10000
    onOpen: ignore